;;;; Created on 2008-04-15 16:09:46

(in-package :clone-ml)



(defun convert-one-model (model kb)
  (let ((case-prefix (format nil "~A~A" (model-name model) (model-version model))))
    (let ((case-id (format nil "case @ ~A" case-prefix)) 
          (context-id (format nil "context @ ~A" case-prefix))
          (conclusion-id (format nil "conclusion @ ~A" case-prefix))
          (protocol-id (format nil "protocol @ ~A" case-prefix))
          (process-id (format nil "process @ ~A" case-prefix))
          (item-id (format nil "item @ ~A" case-prefix))
          (issue-id (format nil "issue @ ~A" case-prefix))
          (proposal-id (format nil "proposal @ ~A" case-prefix)))
      (let ((cas (make-cls case-id :kb kb)))
        (instance-add-direct-type cas 'protege-kb::|:STANDARD-CLASS|)
        (setf (cls-concretep cas) t)
        (cls-add-direct-supercls cas 'onenegotiation-kb::|one_case|))
      (let ((con (make-cls context-id :kb kb)))
        (instance-add-direct-type con 'protege-kb::|:STANDARD-CLASS|)
        (setf (cls-concretep con) t)
        (cls-add-direct-supercls con 'onenegotiation-kb::|one_context|)
        (dolist (attr (neginfo-attributes (model-neginfo model)))
          (add-attribute model kb attr con)))
      (let ((con (make-cls conclusion-id :kb kb)))
        (instance-add-direct-type con 'protege-kb::|:STANDARD-CLASS|)
        (setf (cls-concretep con) t)
        (cls-add-direct-supercls con 'onenegotiation-kb::|one_conclusion|))
      (let ((pro (make-cls protocol-id :kb kb)))
        (instance-add-direct-type pro 'protege-kb::|:STANDARD-CLASS|)
        (setf (cls-concretep pro) t)
        (cls-add-direct-supercls pro 'onenegotiation-kb::|one_protocol|)
        (dolist (attr (protoinfo-attributes (model-protoinfo model)))
          ;(format t "### ~A~%" attr)
          (add-attribute model kb attr pro)))
      (let ((pro (make-cls process-id :kb kb)))
        (instance-add-direct-type pro 'protege-kb::|:STANDARD-CLASS|)
        (setf (cls-concretep pro) t)
        (cls-add-direct-supercls pro 'onenegotiation-kb::|one_process|))
      (let ((pro (make-cls item-id :kb kb)))
        (instance-add-direct-type pro 'protege-kb::|:STANDARD-CLASS|)
        (setf (cls-concretep pro) t)
        (cls-add-direct-supercls pro 'onenegotiation-kb::|one_item|)
        (dolist (attr (item-attributes (infomodel-item (model-infomodel model))))
          (add-attribute model kb attr pro)))
      (let ((pro (make-cls proposal-id :kb kb)))
        (instance-add-direct-type pro 'protege-kb::|:STANDARD-CLASS|)
        (setf (cls-concretep pro) t)
        (cls-add-direct-supercls pro 'onenegotiation-kb::|one_proposal|))
      (let ((iss (make-cls issue-id :kb kb)))
        (instance-add-direct-type iss 'protege-kb::|:STANDARD-CLASS|)
        (setf (cls-concretep iss) t)
        (cls-add-direct-supercls iss 'onenegotiation-kb::|one_issue|)
        (dolist (is (item-issues (infomodel-item (model-infomodel model))))
          (add-issue model kb is issue-id proposal-id))))))


(defun add-issue (model kb is issue-id proposal-id)
  (let ((issuename (format nil "~A @ ~A~A " (issue-name is) (model-name model) (model-version model) )))
    (let ((issue (make-cls issuename :kb kb)))
      (instance-add-direct-type issue 'protege-kb::|:STANDARD-CLASS|)
      (setf (cls-concretep issue) t)
      (cls-add-direct-supercls issue (get-cls issue-id :kb kb))
      (dolist (attr (issue-attributes is))
        (add-attribute model kb attr issue))
      (let ((slotname (format nil "has ~A " issuename )))
        (let ((sl (make-slot slotname :kb kb)))
          (instance-add-direct-type sl 'protege-kb::|:STANDARD-SLOT|)
          (cls-add-direct-template-slot (get-slot proposal-id :kb kb) sl )
          (setf (slot-maximum-cardinality sl) 1)
          (setf (slot-allowed-clses sl) (list issue)))))))

(defun add-attribute (model kb attr item)
  (let ((attrname (format nil "~A @ ~A~A " (attribute-name attr) (model-name model) (model-version model) )))
    (let ((at (make-slot attrname :kb kb)))
      (instance-add-direct-type at 'protege-kb::|:STANDARD-SLOT|)
      (cls-add-direct-template-slot item at)
      (setf (slot-maximum-cardinality at) 1)
      (let ((typ (attribute-onetype attr)))
        (if (not (onetype-globalp typ))
            (let ((typename (onetype-name typ))
                  (kind (onetype-kind typ)))
              (cond
               ((eq kind 'enum)
                (let ((v
                       (mapcan #'(lambda (x) (list x)) (onetype-vals typ))))
                  (setf (slot-allowed-values at) v)))
               ((string= typename "negmod:OneDate")
                (setf (slot-allowed-clses at) '(dataset-kb::|date|)))
               (t
                (format t "Not implemented, yet. \"~A\" ~A~%" typename typ))))
            (let ((typename (onetype-name typ))
                  (kind (onetype-kind typ)))
              (cond 
               ((string= typename "negmod:OneString")
                (setf (frame-own-slot-value at 'protege-kb::|:SLOT-VALUE-TYPE|) "String"))
               ((string= typename "negmod:OneInteger")
                (setf (frame-own-slot-value at 'protege-kb::|:SLOT-VALUE-TYPE|) "Integer"))
               ((string= typename "negmod:OneBoolean")
                (setf (frame-own-slot-value at 'protege-kb::|:SLOT-VALUE-TYPE|) "Boolean"))
               ((string= typename "negmod:OneDate")
                (setf (frame-own-slot-values at 'protege-kb::|:SLOT-VALUE-TYPE|) (list "Instance" 'dataset-kb::|date|)))
               ((string= typename "negmod:OneImage")
                (setf (frame-own-slot-values at 'protege-kb::|:SLOT-VALUE-TYPE|) (list "Instance" 'onenegotiation-kb::|one_image|)))
               ((string= typename "negmod:OneBinaryDocument")
                (setf (frame-own-slot-values at 'protege-kb::|:SLOT-VALUE-TYPE|) (list "Instance" 'onenegotiation-kb::|one_binary_document|)))
               ((string= typename "negmod:OneCurrency")
                (setf (frame-own-slot-value at 'protege-kb::|:SLOT-VALUE-TYPE|) "String"))
               ((string= typename "negmod:OneAmount")
                (setf (frame-own-slot-value at 'protege-kb::|:SLOT-VALUE-TYPE|) "Integer"))
               ((eq kind 'enum)
                (let ((v
                       (mapcan #'(lambda (x) (list x)) (onetype-vals typ))))
                  (setf (slot-allowed-values at) v)))
               (t
                (format t "Not implemented, yet. \"~A\" ~A~%" typename typ))
               ))))
      )))


